[package]
name = "genesis"
version = "0.1.0"
authors = ["onetesseract <onetesseract@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neoncode = {path = "../neoncode"}
proc-macro2 = "=1.0.26"